<a href="https://colab.research.google.com/github/VictoryChianumba/Github-Projects/blob/main/Barclays_predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import requests

In [ ]:
standings_url = "https://fbref.com/en/comps/9/2021-2022/2021-2022-Premier-League-Stats"

In [ ]:
data = requests.get(standings_url)

In [ ]:
from bs4 import BeautifulSoup

In [ ]:
soup = BeautifulSoup(data.text)

In [ ]:
standings_table = soup.select('table.stats_table')[0]

In [ ]:
links = standings_table.find_all('a')

In [ ]:
links = [l.get("href") for l in links]

In [ ]:
links = [l for l in links if '/squads/' in l]

In [ ]:
team_urls = [f"https://fbref.com{l}" for l in links]

In [ ]:
team_urls

['https://fbref.com/en/squads/b8fd03ef/2021-2022/Manchester-City-Stats',
 'https://fbref.com/en/squads/822bd0ba/2021-2022/Liverpool-Stats',
 'https://fbref.com/en/squads/cff3d9bb/2021-2022/Chelsea-Stats',
 'https://fbref.com/en/squads/361ca564/2021-2022/Tottenham-Hotspur-Stats',
 'https://fbref.com/en/squads/18bb7c10/2021-2022/Arsenal-Stats',
 'https://fbref.com/en/squads/19538871/2021-2022/Manchester-United-Stats',
 'https://fbref.com/en/squads/7c21e445/2021-2022/West-Ham-United-Stats',
 'https://fbref.com/en/squads/a2d435b3/2021-2022/Leicester-City-Stats',
 'https://fbref.com/en/squads/d07537b9/2021-2022/Brighton-and-Hove-Albion-Stats',
 'https://fbref.com/en/squads/8cec06e1/2021-2022/Wolverhampton-Wanderers-Stats',
 'https://fbref.com/en/squads/b2b47a98/2021-2022/Newcastle-United-Stats',
 'https://fbref.com/en/squads/47c64c55/2021-2022/Crystal-Palace-Stats',
 'https://fbref.com/en/squads/cd051869/2021-2022/Brentford-Stats',
 'https://fbref.com/en/squads/8602292d/2021-2022/Aston-Villa-Stats',
 'https://fbref.com/en/squads/33c895d4/2021-2022/Southampton-Stats',
 'https://fbref.com/en/squads/d3fd31cc/2021-2022/Everton-Stats',
 'https://fbref.com/en/squads/5bfb9659/2021-2022/Leeds-United-Stats',
 'https://fbref.com/en/squads/943e8050/2021-2022/Burnley-Stats',
 'https://fbref.com/en/squads/2abfe087/2021-2022/Watford-Stats',
 'https://fbref.com/en/squads/1c781004/2021-2022/Norwich-City-Stats']

In [ ]:
team_url = team_urls[0]

In [ ]:
data = requests.get(team_url)

In [ ]:
matches = pd.read_html(data.text, match ="Scores & Fixtures")

In [ ]:
matches[0].head()

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,xG,xGA,Poss,Attendance,Captain,Formation,Referee,Match Report,Notes
0,2021-08-07,17:15,Community Shield,FA Community Shield,Sat,Neutral,L,0,1,Leicester City,NaN,NaN,57,NaN,Fernandinho,4-3-3,Paul Tierney,Match Report,NaN
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0,1,Tottenham,1.8,1.0,65,58262.0,Fernandinho,4-3-3,Anthony Taylor,Match Report,NaN
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5,0,Norwich City,2.6,0.1,67,51437.0,İlkay Gündoğan,4-3-3,Graham Scott,Match Report,NaN
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,Arsenal,4.4,0.2,80,52276.0,İlkay Gündoğan,4-3-3,Martin Atkinson,Match Report,NaN
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,Leicester City,2.8,0.6,61,32087.0,İlkay Gündoğan,4-3-3,Paul Tierney,Match Report,NaN

In [ ]:
soup = BeautifulSoup(data.text)

In [ ]:
links = soup.find_all('a')

In [ ]:
links = [l.get("href") for l in links]

In [ ]:
links = [l for l in links if l and 'all_comps/shooting/'in l]

In [ ]:
links

['/en/squads/b8fd03ef/2021-2022/matchlogs/all_comps/shooting/Manchester-City-Match-Logs-All-Competitions',
 '/en/squads/b8fd03ef/2021-2022/matchlogs/all_comps/shooting/Manchester-City-Match-Logs-All-Competitions',
 '/en/squads/b8fd03ef/2021-2022/matchlogs/all_comps/shooting/Manchester-City-Match-Logs-All-Competitions',
 '/en/squads/b8fd03ef/2021-2022/matchlogs/all_comps/shooting/Manchester-City-Match-Logs-All-Competitions']

In [ ]:
data = requests.get(f"https://fbref.com{links[0]}")

In [ ]:
shooting = pd.read_html(data.text, match = "Shooting")[0]

In [ ]:
shooting.head()

  For Manchester City                                                     \
                 Date   Time              Comp                Round  Day
0          2021-08-07  17:15  Community Shield  FA Community Shield  Sat
1          2021-08-15  16:30    Premier League          Matchweek 1  Sun
2          2021-08-21  15:00    Premier League          Matchweek 2  Sat
3          2021-08-28  12:30    Premier League          Matchweek 3  Sat
4          2021-09-11  15:00    Premier League          Matchweek 4  Sat

                                         ... Standard               Expected  \
     Venue Result GF GA        Opponent  ...     Dist   FK PK PKatt       xG
0  Neutral      L  0  1  Leicester City  ...      NaN  NaN  0     0      NaN
1     Away      L  0  1       Tottenham  ...     17.3  1.0  0     0      1.8
2     Home      W  5  0    Norwich City  ...     18.5  1.0  0     0      2.6
3     Home      W  5  0         Arsenal  ...     14.8  0.0  0     0      4.4
4     Away      W  1  0  Leicester City  ...     14.3  0.0  0     0      2.8

                            Unnamed: 25_level_0
  npxG npxG/Sh G-xG np:G-xG        Match Report
0  NaN     NaN  NaN     NaN        Match Report
1  1.8    0.10 -1.8    -1.8        Match Report
2  2.6    0.17  1.4     1.4        Match Report
3  4.4    0.18  0.6     0.6        Match Report
4  2.8    0.12 -1.8    -1.8        Match Report

[5 rows x 26 columns]

In [ ]:
shooting.columns = shooting.columns.droplevel()

In [ ]:
shooting.head()

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Match Report
0,2021-08-07,17:15,Community Shield,FA Community Shield,Sat,Neutral,L,0,1,Leicester City,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,Match Report
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0,1,Tottenham,...,17.3,1.0,0,0,1.8,1.8,0.10,-1.8,-1.8,Match Report
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5,0,Norwich City,...,18.5,1.0,0,0,2.6,2.6,0.17,1.4,1.4,Match Report
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,Arsenal,...,14.8,0.0,0,0,4.4,4.4,0.18,0.6,0.6,Match Report
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,Leicester City,...,14.3,0.0,0,0,2.8,2.8,0.12,-1.8,-1.8,Match Report

In [ ]:
team_data = matches[0].merge(shooting[["Date", "Sh", "SoT", "Dist", "FK", "PK", "PKatt"]], on="Date")

In [ ]:
team_data.head()

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Formation,Referee,Match Report,Notes,Sh,SoT,Dist,FK,PK,PKatt
0,2021-08-07,17:15,Community Shield,FA Community Shield,Sat,Neutral,L,0,1,Leicester City,...,4-3-3,Paul Tierney,Match Report,NaN,12,3,NaN,NaN,0,0
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0,1,Tottenham,...,4-3-3,Anthony Taylor,Match Report,NaN,18,4,17.3,1.0,0,0
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5,0,Norwich City,...,4-3-3,Graham Scott,Match Report,NaN,16,4,18.5,1.0,0,0
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,Arsenal,...,4-3-3,Martin Atkinson,Match Report,NaN,25,10,14.8,0.0,0,0
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,Leicester City,...,4-3-3,Paul Tierney,Match Report,NaN,25,8,14.3,0.0,0,0

In [ ]:
years = list(range(2022, 2020, -1))

In [ ]:
years

[2022, 2021]

In [ ]:
all_matches = []

In [ ]:
standings_url = "https://fbref.com/en/comps/9/2021-2022/2021-2022-Premier-League-Stats"

In [ ]:
import time

for year in years:
  data = requests.get(standings_url)
  soup = BeautifulSoup(data.text)
  standings_table = soup.select('table.stats_table')[0]

  links = [l.get("href") for l in standings_table.find_all('a')]
  links = [l for l in links if '/squads/' in l]
  team_urls = [f"https://fbref.com{l}" for l in links]

  previous_season = soup.select("a.prev")[0].get("href")
  standings_url = f"https://fbref.com{previous_season}"

  for team_url in team_urls:
    team_name = team_url.split("/")[-1].replace("-Stats", "").replace("-", " ")

    data = requests.get(team_url)
    matches = pd.read_html(data.text, match = "Scores & Fixtures")[0]

    soup = BeautifulSoup(data.text)
    links = [l.get("href") for l in soup.find_all('a')]
    links = [l for l in links if l and 'all_comps/shooting/'in l]
    data = requests.get(f"https://fbref.com{links[0]}")
    shooting = pd.read_html(data.text, match = "Shooting")[0]
    shooting.columns = shooting.columns.droplevel()

    try:
      team_data = matches.merge(shooting[["Date", "Sh", "SoT", "Dist", "FK", "PK", "PKatt"]], on="Date")
    except ValueError:
      continue

    team_data = team_data[team_data["Comp"] == "Premier League"]
    team_data["Season"] = year
    team_data["Team"] = team_name
    all_matches.append(team_data)
    time.sleep(1)

<ipython-input-51-98c012b531ca>:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_data["Season"] = year
<ipython-input-51-98c012b531ca>:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_data["Team"] = team_name

In [ ]:
match_df = pd.concat(all_matches)

In [ ]:
match_df

In [ ]:
match_df.columns = [c.lower() for c in match_df.columns]

In [ ]:
match_df.to_csv("matches.csv")

# Finished web scrapping
# Now predicting the league

In [ ]:
matches  = pd.read_csv("matches.csv", index_col = 0)

In [ ]:
matches.head()

In [ ]:
matches.shape

(1520, 27)

In [ ]:
matches["team"].value_counts()

In [ ]:
matches["round"].value_counts()

In [ ]:
matches.dtypes

In [ ]:
matches["date"] = pd.to_datetime(matches["date"])

In [ ]:
matches

In [ ]:
matches.dtypes

In [ ]:
matches["venue_code"] = matches["venue"].astype("category").cat.codes

In [ ]:
matches

In [ ]:
matches["opp_code"] = matches["opponent"].astype("category").cat.codes

In [ ]:
matches

In [ ]:
matches["hour"] = matches["time"].str.replace(":.+", "", regex=True).astype("int")

In [ ]:
matches.head()

In [ ]:
matches["day_code"] = matches["date"].dt.dayofweek

In [ ]:
matches

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0,1,Tottenham,...,1.0,0.0,0.0,2022,Manchester City,0,18,16,6,0
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5,0,Norwich City,...,1.0,0.0,0.0,2022,Manchester City,1,15,15,5,1
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,Arsenal,...,0.0,0.0,0.0,2022,Manchester City,1,0,12,5,1
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,Leicester City,...,0.0,0.0,0.0,2022,Manchester City,0,10,15,5,1
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0,0,Southampton,...,1.0,0.0,0.0,2022,Manchester City,1,17,15,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2021-05-02,19:15,Premier League,Matchweek 34,Sun,Away,L,0,4,Tottenham,...,0.0,0.0,0.0,2021,Sheffield United,0,18,19,6,0
39,2021-05-08,15:00,Premier League,Matchweek 35,Sat,Home,L,0,2,Crystal Palace,...,1.0,0.0,0.0,2021,Sheffield United,1,6,15,5,0
40,2021-05-16,19:00,Premier League,Matchweek 36,Sun,Away,W,1,0,Everton,...,0.0,0.0,0.0,2021,Sheffield United,0,7,19,6,1
41,2021-05-19,18:00,Premier League,Matchweek 37,Wed,Away,L,0,1,Newcastle Utd,...,1.0,0.0,0.0,2021,Sheffield United,0,14,18,2,0
42,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,1,0,Burnley,...,0.0,0.0,0.0,2021,Sheffield United,1,4,16,6,1

In [ ]:
matches["target"] = (matches["result"] == "W").astype("int")

In [ ]:
matches.head()

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rf = RandomForestClassifier(n_estimators = 50, min_samples_split=10, random_state =1)

In [ ]:
train = matches[matches["date"] < '2022-01-01']

In [ ]:
test = matches[matches["date"] > '2022-01-01']

In [ ]:
predictors = ["venue_code", "opp_code", "hour", "day_code"]

In [ ]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [ ]:
preds = rf.predict(test[predictors])

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
acc = accuracy_score(test["target"], preds)

In [ ]:
acc

0.6056701030927835

In [ ]:
combined = pd.DataFrame(dict(actual=test["target"], prediction = preds))

In [ ]:
pd.crosstab(index=combined["actual"], columns = combined["prediction"])

prediction    0   1
actual
0           186  47
1           106  49

In [ ]:
from sklearn.metrics import precision_score

In [ ]:
precision_score(test["target"], preds)

0.5104166666666666

In [ ]:
grouped_matches = matches.groupby("team")

In [ ]:
group = grouped_matches.get_group("Manchester  City")

In [ ]:
group

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0,1,Tottenham,...,1.0,0.0,0.0,2022,Manchester City,0,18,16,6,0
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5,0,Norwich City,...,1.0,0.0,0.0,2022,Manchester City,1,15,15,5,1
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,Arsenal,...,0.0,0.0,0.0,2022,Manchester City,1,0,12,5,1
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,Leicester City,...,0.0,0.0,0.0,2022,Manchester City,0,10,15,5,1
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0,0,Southampton,...,1.0,0.0,0.0,2022,Manchester City,1,17,15,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54,2021-05-01,12:30,Premier League,Matchweek 34,Sat,Away,W,2,0,Crystal Palace,...,1.0,0.0,0.0,2021,Manchester City,0,6,12,5,1
56,2021-05-08,17:30,Premier League,Matchweek 35,Sat,Home,L,1,2,Chelsea,...,0.0,0.0,1.0,2021,Manchester City,1,5,17,5,0
57,2021-05-14,20:00,Premier League,Matchweek 36,Fri,Away,W,4,3,Newcastle Utd,...,1.0,0.0,0.0,2021,Manchester City,0,14,20,4,1
58,2021-05-18,19:00,Premier League,Matchweek 37,Tue,Away,L,2,3,Brighton,...,1.0,0.0,0.0,2021,Manchester City,0,3,19,1,0
59,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,5,0,Everton,...,0.0,0.0,0.0,2021,Manchester City,1,7,16,6,1

In [ ]:
def rolling_averages(group, cols, new_cols):
  group = group.sort_values("date")
  rolling_stats = group[cols].rolling(3, closed='left').mean()
  group[new_cols] = rolling_stats
  group = group.dropna(subset=new_cols)
  return group

In [ ]:
cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt"]
new_cols = [f"{c}_colling" for c in cols]

In [ ]:
new_cols

['gf_colling',
 'ga_colling',
 'sh_colling',
 'sot_colling',
 'dist_colling',
 'fk_colling',
 'pk_colling',
 'pkatt_colling']

In [ ]:
rolling_averages(group, cols, new_cols)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_colling,ga_colling,sh_colling,sot_colling,dist_colling,fk_colling,pk_colling,pkatt_colling
5,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Home,W,1,0,Arsenal,...,5,1,2.000000,2.333333,17.333333,4.666667,19.700000,1.333333,0.333333,0.333333
7,2020-10-24,12:30,Premier League,Matchweek 6,Sat,Away,D,1,1,West Ham,...,5,0,1.333333,2.000000,17.333333,3.666667,18.566667,0.666667,0.000000,0.000000
9,2020-10-31,12:30,Premier League,Matchweek 7,Sat,Away,W,1,0,Sheffield Utd,...,5,1,1.000000,0.666667,16.666667,4.333333,18.933333,0.666667,0.000000,0.000000
11,2020-11-08,16:30,Premier League,Matchweek 8,Sun,Home,D,1,1,Liverpool,...,6,0,1.000000,0.333333,14.333333,6.666667,19.033333,1.000000,0.000000,0.000000
12,2020-11-21,17:30,Premier League,Matchweek 9,Sat,Away,L,0,2,Tottenham,...,5,0,1.000000,0.666667,12.000000,5.666667,20.000000,1.000000,0.000000,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52,2022-04-30,17:30,Premier League,Matchweek 35,Sat,Away,W,4,0,Leeds United,...,5,1,3.333333,1.000000,16.000000,5.333333,17.466667,0.333333,0.333333,0.333333
54,2022-05-08,16:30,Premier League,Matchweek 36,Sun,Home,W,5,0,Newcastle Utd,...,6,1,4.000000,0.333333,18.666667,6.000000,16.933333,0.000000,0.333333,0.333333
55,2022-05-11,20:15,Premier League,Matchweek 33,Wed,Away,W,5,1,Wolves,...,2,1,4.666667,0.333333,20.000000,7.333333,15.600000,0.333333,0.333333,0.333333
56,2022-05-15,14:00,Premier League,Matchweek 37,Sun,Away,D,2,2,West Ham,...,6,0,4.666667,0.333333,18.333333,6.666667,15.633333,0.333333,0.000000,0.000000
57,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Home,W,3,2,Aston Villa,...,6,1,4.000000,1.000000,22.000000,7.000000,16.433333,1.000000,0.000000,0.333333

In [ ]:
matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))

In [ ]:
matches_rolling

                                  date   time            comp         round  \
team
Arsenal                  6  2020-10-04  14:00  Premier League   Matchweek 4
                         7  2020-10-17  17:30  Premier League   Matchweek 5
                         9  2020-10-25  19:15  Premier League   Matchweek 6
                         11 2020-11-01  16:30  Premier League   Matchweek 7
                         13 2020-11-08  19:15  Premier League   Matchweek 8
...                                ...    ...             ...           ...
Wolverhampton  Wanderers 37 2022-04-30  15:00  Premier League  Matchweek 35
                         38 2022-05-07  15:00  Premier League  Matchweek 36
                         39 2022-05-11  20:15  Premier League  Matchweek 33
                         40 2022-05-15  14:00  Premier League  Matchweek 37
                         41 2022-05-22  16:00  Premier League  Matchweek 38

                             day venue result  gf  ga         opponent  ...  \
team                                                                    ...
Arsenal                  6   Sun  Home      W   2   1    Sheffield Utd  ...
                         7   Sat  Away      L   0   1  Manchester City  ...
                         9   Sun  Home      L   0   1   Leicester City  ...
                         11  Sun  Away      W   1   0   Manchester Utd  ...
                         13  Sun  Home      L   0   3      Aston Villa  ...
...                          ...   ...    ...  ..  ..              ...  ...
Wolverhampton  Wanderers 37  Sat  Home      L   0   3         Brighton  ...
                         38  Sat  Away      D   2   2          Chelsea  ...
                         39  Wed  Home      L   1   5  Manchester City  ...
                         40  Sun  Home      D   1   1     Norwich City  ...
                         41  Sun  Away      L   1   3        Liverpool  ...

                             day_code  target  gf_colling  ga_colling  \
team
Arsenal                  6          6       1    2.000000    1.333333
                         7          5       0    1.666667    1.666667
                         9          6       0    1.000000    1.666667
                         11         6       1    0.666667    1.000000
                         13         6       0    0.333333    0.666667
...                               ...     ...         ...         ...
Wolverhampton  Wanderers 37         5       0    0.666667    1.000000
                         38         5       0    0.000000    1.666667
                         39         2       0    0.666667    2.000000
                         40         6       0    1.000000    3.333333
                         41         6       0    1.333333    2.666667

                            sh_colling sot_colling dist_colling fk_colling  \
team
Arsenal                  6    8.000000    3.666667    14.633333   0.666667
                         7    5.666667    3.666667    15.366667   0.000000
                         9    7.000000    3.666667    16.566667   0.666667
                         11   9.666667    4.000000    16.566667   1.000000
                         13   9.666667    2.666667    19.333333   1.000000
...                                ...         ...          ...        ...
Wolverhampton  Wanderers 37   8.666667    3.333333    17.400000   0.000000
                         38   8.666667    2.333333    18.633333   0.333333
                         39  11.666667    3.000000    17.766667   0.333333
                         40  10.666667    2.666667    17.066667   0.333333
                         41  12.666667    3.666667    17.766667   0.333333

                             pk_colling  pkatt_colling
team
Arsenal                  6     0.000000       0.000000
                         7     0.000000       0.000000
                         9     0.000000       0.000000
                         11    0.000000       0.000000
                         13    0.333333       0.333333
...                                 ...            ...
Wolverhampton  Wanderers 37    0.000000       0.000000
                         38    0.000000       0.000000
                         39    0.000000       0.000000
                         40    0.000000       0.000000
                         41    0.000000       0.000000

[1448 rows x 40 columns]

In [ ]:
matches_rolling = matches_rolling.droplevel("team")

In [ ]:
matches_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_colling,ga_colling,sh_colling,sot_colling,dist_colling,fk_colling,pk_colling,pkatt_colling
6,2020-10-04,14:00,Premier League,Matchweek 4,Sun,Home,W,2,1,Sheffield Utd,...,6,1,2.000000,1.333333,8.000000,3.666667,14.633333,0.666667,0.000000,0.000000
7,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Away,L,0,1,Manchester City,...,5,0,1.666667,1.666667,5.666667,3.666667,15.366667,0.000000,0.000000,0.000000
9,2020-10-25,19:15,Premier League,Matchweek 6,Sun,Home,L,0,1,Leicester City,...,6,0,1.000000,1.666667,7.000000,3.666667,16.566667,0.666667,0.000000,0.000000
11,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Away,W,1,0,Manchester Utd,...,6,1,0.666667,1.000000,9.666667,4.000000,16.566667,1.000000,0.000000,0.000000
13,2020-11-08,19:15,Premier League,Matchweek 8,Sun,Home,L,0,3,Aston Villa,...,6,0,0.333333,0.666667,9.666667,2.666667,19.333333,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37,2022-04-30,15:00,Premier League,Matchweek 35,Sat,Home,L,0,3,Brighton,...,5,0,0.666667,1.000000,8.666667,3.333333,17.400000,0.000000,0.000000,0.000000
38,2022-05-07,15:00,Premier League,Matchweek 36,Sat,Away,D,2,2,Chelsea,...,5,0,0.000000,1.666667,8.666667,2.333333,18.633333,0.333333,0.000000,0.000000
39,2022-05-11,20:15,Premier League,Matchweek 33,Wed,Home,L,1,5,Manchester City,...,2,0,0.666667,2.000000,11.666667,3.000000,17.766667,0.333333,0.000000,0.000000
40,2022-05-15,14:00,Premier League,Matchweek 37,Sun,Home,D,1,1,Norwich City,...,6,0,1.000000,3.333333,10.666667,2.666667,17.066667,0.333333,0.000000,0.000000
41,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Away,L,1,3,Liverpool,...,6,0,1.333333,2.666667,12.666667,3.666667,17.766667,0.333333,0.000000,0.000000

In [ ]:
matches_rolling.index = range(matches_rolling.shape[0])

In [ ]:
matches_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_colling,ga_colling,sh_colling,sot_colling,dist_colling,fk_colling,pk_colling,pkatt_colling
0,2020-10-04,14:00,Premier League,Matchweek 4,Sun,Home,W,2,1,Sheffield Utd,...,6,1,2.000000,1.333333,8.000000,3.666667,14.633333,0.666667,0.000000,0.000000
1,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Away,L,0,1,Manchester City,...,5,0,1.666667,1.666667,5.666667,3.666667,15.366667,0.000000,0.000000,0.000000
2,2020-10-25,19:15,Premier League,Matchweek 6,Sun,Home,L,0,1,Leicester City,...,6,0,1.000000,1.666667,7.000000,3.666667,16.566667,0.666667,0.000000,0.000000
3,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Away,W,1,0,Manchester Utd,...,6,1,0.666667,1.000000,9.666667,4.000000,16.566667,1.000000,0.000000,0.000000
4,2020-11-08,19:15,Premier League,Matchweek 8,Sun,Home,L,0,3,Aston Villa,...,6,0,0.333333,0.666667,9.666667,2.666667,19.333333,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1443,2022-04-30,15:00,Premier League,Matchweek 35,Sat,Home,L,0,3,Brighton,...,5,0,0.666667,1.000000,8.666667,3.333333,17.400000,0.000000,0.000000,0.000000
1444,2022-05-07,15:00,Premier League,Matchweek 36,Sat,Away,D,2,2,Chelsea,...,5,0,0.000000,1.666667,8.666667,2.333333,18.633333,0.333333,0.000000,0.000000
1445,2022-05-11,20:15,Premier League,Matchweek 33,Wed,Home,L,1,5,Manchester City,...,2,0,0.666667,2.000000,11.666667,3.000000,17.766667,0.333333,0.000000,0.000000
1446,2022-05-15,14:00,Premier League,Matchweek 37,Sun,Home,D,1,1,Norwich City,...,6,0,1.000000,3.333333,10.666667,2.666667,17.066667,0.333333,0.000000,0.000000
1447,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Away,L,1,3,Liverpool,...,6,0,1.333333,2.666667,12.666667,3.666667,17.766667,0.333333,0.000000,0.000000

In [ ]:
def make_predictions(data, predictors):
  train = data[data["date"] < '2022-01-01']
  test = data[data["date"] > '2022-01-01']
  rf.fit(train[predictors], train["target"])
  preds = rf.predict(test[predictors])
  combined = pd.DataFrame(dict(actual = test["target"], predicted = preds), index = test.index)
  precision = precision_score(test["target"], preds)
  return combined, precision

In [ ]:
combined, precision = make_predictions(matches_rolling, predictors + new_cols )

In [ ]:
precision

0.5238095238095238

In [ ]:
combined

      actual  predicted
55         0          0
56         1          0
57         1          0
58         1          1
59         1          1
...      ...        ...
1443       0          0
1444       0          0
1445       0          0
1446       0          0
1447       0          0

[388 rows x 2 columns]

In [ ]:
combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index = True, right_index = True)

In [ ]:
combined

,actual,predicted,date,team,opponent,result
55,0,0,2022-01-23,Arsenal,Burnley,D
56,1,0,2022-02-10,Arsenal,Wolves,W
57,1,0,2022-02-19,Arsenal,Brentford,W
58,1,1,2022-02-24,Arsenal,Wolves,W
59,1,1,2022-03-06,Arsenal,Watford,W
...,...,...,...,...,...,...
1443,0,0,2022-04-30,Wolverhampton Wanderers,Brighton,L
1444,0,0,2022-05-07,Wolverhampton Wanderers,Chelsea,D
1445,0,0,2022-05-11,Wolverhampton Wanderers,Manchester City,L
1446,0,0,2022-05-15,Wolverhampton Wanderers,Norwich City,D
1447,0,0,2022-05-22,Wolverhampton Wanderers,Liverpool,L

In [ ]:
class MissingDict(dict):
  __missing__ = lambda self, key: key

map_values = {
    "Brighton and Hove Albion" : "Brighton",
    "Manchester United" : "Manchester Utd",
    "Newcastle United " : "Newcastle Utd",
    "Tottenham Hotspur": "Tottenham",
    "West Ham United": "West Ham",
    "Wolverhampton Wanderers": "Wolves"

}

mapping = MissingDict(**map_values)

In [ ]:
mapping["Arsenal"]

'Arsenal'

In [ ]:
combined ["new_team"] = combined["team"].map(mapping)

In [ ]:
combined

,actual,predicted,date,team,opponent,result,new_team
55,0,0,2022-01-23,Arsenal,Burnley,D,Arsenal
56,1,0,2022-02-10,Arsenal,Wolves,W,Arsenal
57,1,0,2022-02-19,Arsenal,Brentford,W,Arsenal
58,1,1,2022-02-24,Arsenal,Wolves,W,Arsenal
59,1,1,2022-03-06,Arsenal,Watford,W,Arsenal
...,...,...,...,...,...,...,...
1443,0,0,2022-04-30,Wolverhampton Wanderers,Brighton,L,Wolverhampton Wanderers
1444,0,0,2022-05-07,Wolverhampton Wanderers,Chelsea,D,Wolverhampton Wanderers
1445,0,0,2022-05-11,Wolverhampton Wanderers,Manchester City,L,Wolverhampton Wanderers
1446,0,0,2022-05-15,Wolverhampton Wanderers,Norwich City,D,Wolverhampton Wanderers
1447,0,0,2022-05-22,Wolverhampton Wanderers,Liverpool,L,Wolverhampton Wanderers

In [ ]:
merged = combined.merge(combined, left_on = ["date", "new_team"], right_on = ["date", "opponent"])

In [ ]:
merged[(merged["predicted_x"] == 1) & (merged["predicted_y"] == 0)]["actual_x"].value_counts()

1    22
0    16
Name: actual_x, dtype: int64